pipeline:
  name: Example from GitX Template
  identifier: Example_from_GitX_Template
  template:
    templateRef: account.Simple_Example_Template
    versionLabel: 1.0.0
    templateInputs:
      stages:
        - stage:
            identifier: Hello_World
            type: Deployment
            spec:
              service:
                serviceRef: testservice
              environment:
                environmentRef: testenv
                infrastructureDefinitions:
                  - identifier: testinfradef
      variables:
        - name: message
          type: String
          value: <+input>
  tags: {}
  projectIdentifier: Test_Bed
  orgIdentifier: default

